a.out : main.o insert.o display.o delete.o
	cc main.o insert.o display.o delete.o
main.o : main.c
	cc -c main.c
insert.o : insert.c
	cc -c insert.c
display.o : display.c
	cc -c display.c
delete.o : delete.c
	cc -c delete.c
